# Generated by Django 3.1.2 on 2020-10-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20201019_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Reservation',
        ),
    ]
