# Generated by Django 3.1.2 on 2020-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_auto_20201019_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='double_field',
            field=models.BooleanField(default=True),
        ),
    ]
