# Generated by Django 3.1.2 on 2020-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_auto_20201019_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
