# Generated by Django 3.1.2 on 2020-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0009_auto_20201019_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='full_hour',
            field=models.BooleanField(default=True),
        ),
    ]
