# Generated by Django 3.1.2 on 2020-10-24 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0011_reservation_player1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='player1',
            field=models.OneToOneField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palyer1', to=settings.AUTH_USER_MODEL),
        ),
    ]
