# Generated by Django 3.1.2 on 2020-10-24 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0012_auto_20201024_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='player2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palyer2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='player3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palyer3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='player4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palyer4', to=settings.AUTH_USER_MODEL),
        ),
    ]
